* Create a git repo
You can create a git repo with M-x magit-init

#+BEGIN_SRC emacs-lisp
(magit-init)
#+END_SRC

* Check the status of your repo
Run M-x magit-status to see the status of your repo.

Press g in the window to refresh it.

press "n" (next) or "p" (previous) to navigate in this window.

* Stage a file
In the magit-status window, put your cursor on an unstaged file and press "s".

If you press TAB on the file, it will expand to show the changes that are unstaged. Deletions show in red, and additions in green. The changes are in "hunks".

* Commit a file
In the magit-status window with some files that are staged, press "c", review the options, and probably press "c" again. Enter a commit message and type "C-c C-c" to commit it, or "C-c C-k" to cancel it.

* Diffs
From the magit-status window, with the cursor on some file, press "d" then "d"

* See the log
In the magit-status window press "l", review the options, and press "l" again.

If you want to see only the commits that affected a file, in the magit-status window press "l" then "=f", enter the filename, and then press "l" again.

* Checkout a branch
In the magit-status window press "b".

* Checkout an existing branch.
In the magit-status window press "b" then "b" and choose the branch.

* Checkout a new branch
In the magit-status window press "b" then "c". Choose the branch to start from then a name for the new branch.

* Merge two branches
In the magit-status window press "m", then "m" and select the branch to merge into the current one.

* Checkout an older version of a file
Use M-x magit-checkout-file select the branch, or enter a revision, and then choose a file.

* Add a remote
M-x magit-remote-add
then enter an alias, and the url.

* Push
In the magit-status window press "P" then "p".

* Pull
In the magit-status window press "f" then "p".

* Revert a commit
Got to the log, select the commit and type "V" then "V".

* Rebasing interactively

Open the log, select the oldest commit you want to rebase on then press "r" and then "i". Use M-p and M-n to move commits around. Press "s" on any commits you want to squash into the commit above it. C-c C-c will start the commands.
